version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    env_file:
      - .env
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0-alpine
    command:
      - redis-server


  auth_api:
    container_name: auth_api
    build:
      context: flask_app
    image: flask_app
    depends_on:
      - redis
      - postgres
    ports:
      - 5001:5001
    expose:
      - "5001"