version: '3'

services:
  postgres:
    container_name: postgres_db
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./postgresql/data:/var/lib/postgresql/data

  redis:
    container_name: redis
    image: redis:7.0-alpine
    command:
      - redis-server
    ports:
      - 6379:6379