version: '3'

services:
  postgres:
    container_name: postgres_db_test
    image: postgres:13
    restart: always
    ports:
      - "5432:5432"
    env_file:
      - .env
    expose:
      - "5432"
    volumes:
      - ./postgresql_test/data:/var/lib/postgresql/data

  redis:
    container_name: redis_test
    image: redis:7.0-alpine
    command:
      - redis-server
    ports:
      - 6379:6379

  auth_api:
    container_name: auth_api_test
    build:
      context: flask_app
    image: flask_app
    depends_on:
      - redis
      - postgres

  tests:
    container_name: tests
    image: flask_app
    network_mode: "host"
    entrypoint: >
      sh -c "python3 -m pip install --upgrade pip
      && pip install --default-timeout=100 -r /tests/requirements.txt
      && python3 /tests/utils/wait_for_redis.py
      && python3 /tests/utils/wait_for_api.py
      && pytest -rfe -v  /tests/src/tests_main.py"
    depends_on:
      - auth_api